FROM centos:7.9.2009

WORKDIR .

RUN yum update -y && \
    yum install -y \
        gcc-4.8.5 \
        valgrind-3.15.0 \
        python-2.7.5 \
        python-3.6.8 \
        git-2.26.2 \
        gdb-7.6.1 \
        make-3.82 \
        zip-3.0


